name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.10.0
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fixnum: ^1.0.1
  googleapis_auth: ^1.3.1
  grpc: ^3.1.0
  http: ^0.13.1
  protobuf: ^2.0.1

dev_dependencies:
  test: ^1.22.1
  lints: ^2.0.0
