name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.10.0
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fixnum: ^1.1.0
  googleapis_auth: ^1.4.1
  grpc: ^3.2.3
  http: '>=0.13.0 <2.0.0'
  protobuf: ^3.0.0

dev_dependencies:
  lints: any
  test: any

  # Create custom auth token for testing
  firebase_admin: ^0.2.0
